//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class route
    {
        public int id { get; set; }
        public string place_start { get; set; }
        public string description { get; set; }
        public Nullable<int> province_id { get; set; }
        public Nullable<double> costs { get; set; }
        public Nullable<int> journey_id { get; set; }
    
        public virtual journey journey { get; set; }
        public virtual province province { get; set; }
    }
}
